# This playbook is responsible for deploying Bioregistra Artifacts to the staging and test environments.

---

- hosts: linux
  strategy: free
  serial: 10
  become_method: runas
  gather_facts: false
  
  vars:
    app_name: '{{ instance }}'

  tasks:
  - name: Include variable file
    include_vars:
      file: 'vars/artifacts.yml'

  - name: get the aws credentials
    shell: aws ecr get-login-password | docker login -u AWS --password-stdin "https://$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.us-east-1.amazonaws.com"
      
  

  

  

    
