# This playbook is responsible for deploying Bioregistra Artifacts to the staging and test environments.

---

- hosts: linux
  strategy: free
  serial: 10
  become_method: runas
  gather_facts: false
  
  vars:
    app_name: '{{ instance }}'

  tasks:
  - name: Include variable file
    include_vars:
      file: 'vars/artifacts.yml'

  - name: Create backup directory if it doesn't exist
    file: {path: '{{ backup_path }}', state: directory}
    ignore_errors: yes
  

  

  

    
